# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name (set in params.yaml under hugoblox.branding.name)
title: 'Pedrohentec | Data Engineer'
# Website URL
baseURL: 'https://example.com/'

############################
## LANGUAGE
############################

defaultContentLanguage: pt

languages:
  pt:
    languageName: PT
    weight: 1
    contentDir: content/pt
    title: 'Pedrohentec | Engenheiro de Dados'
  en:
    languageName: EN
    weight: 2
    contentDir: content/en
    title: 'Pedrohentec | Data Engineer'
    menus:
      main:
        - name: Home
          url: /en/
          weight: 10
        - name: Experience
          url: /en/experience/
          weight: 20
        - name: Projects
          url: /en/projects/
          weight: 30
        - name: Courses
          url: /en/courses/
          weight: 40

############################
## PAGE OPTIONS
############################

cascade:
  - _target:
      path: /slides/**
      kind: page
    outputs: [HTML, present]

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
