# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Home
#     url: /
#     weight: 10
#   # - name: Papers
#   #   url: /#papers
#   #   weight: 11
#   # - name: Talks
#   #   url: /#talks
#   #   weight: 12
#   # - name: News
#   #   url: /#news
#   #   weight: 13
#   - name: Experience
#     url: experience/
#     weight: 20
#   - name: Projects
#     url: projects/
#     weight: 30
#   - name: Courses
#     url: courses/
#     weight: 40


main:
  - name: Início
    url: /
    weight: 10
  - name: Experiência
    url: /experience/
    weight: 20
  - name: Projetos
    url: /projects/
    weight: 30
  - name: Cursos
    url: /courses/
    weight: 40

main.en:
  - name: Home
    url: /en/
    weight: 10
  - name: Experience
    url: /en/experience/
    weight: 20
  - name: Projects
    url: /en/projects/
    weight: 30
  - name: Courses
    url: /en/courses/
    weight: 40